meta_product_name: "Repay the Delay"
meta_title: "Repay the Delay - Making train compensation easy"
meta_description: "Relevant description"
meta_image: "meta-pic.jpg" # should exist in `app/assets/images/`
